image: go1.3
git:
  path: github.com/garyburd/redigo
script:
  - cd redis
  - go build
  - go test -v

services:
  - library/redis:2.8.20



# demo 0.4 yaml

clone:
  path: github.com/garyburd/redigo

build:
  image: golang:$$go_version
  environment:
    - GOPATH=/drone
  commands:
    - go version
    - cd redis
    - go build
    - go test -v

compose:
  redis:
    image: redis:$$redis_version

matrix:
  redis_version:
    - 2.8
    - latest
  go_version:
    - 1.3.3
    - 1.4.2
